displayName=Bronzeman PVP TCG
author=0xG3r4rD
description=A PVP based bronzeman TCG plugin. Based on the OSRS TCG & Bronzeman TCG plugin. \
Adjustable gamemodes -> Hard mode (250 tokens per 100k pk'd). \
Adjustable defence levels where rolls are adjusted to your defence level.
tags=tcg,cards,collection,packs,bronzeman,pvp,pk,pking
version=1.12.1
plugins=com.bronzemanpvptcg.OsrsTcgPlugin
build=standard
